/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CustomOrderRouteImport } from './routes/custom-order'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiWoocommerceProductsRouteImport } from './routes/api/woocommerce/products'
import { Route as ApiWoocommerceOrdersRouteImport } from './routes/api/woocommerce/orders'
import { Route as ApiWoocommerceCategoriesRouteImport } from './routes/api/woocommerce/categories'
import { Route as ApiWallistanProductsRouteImport } from './routes/api/wallistan/products'
import { Route as ApiWallistanOrdersRouteImport } from './routes/api/wallistan/orders'
import { Route as ApiWallistanCategoriesRouteImport } from './routes/api/wallistan/categories'
import { Route as ApiWoocommerceProductSlugRouteImport } from './routes/api/woocommerce/product.$slug'
import { Route as ApiWoocommerceOrdersLookupRouteImport } from './routes/api/woocommerce/orders.lookup'
import { Route as ApiWoocommerceOrdersIdRouteImport } from './routes/api/woocommerce/orders.$id'
import { Route as ApiWallistanProductSlugRouteImport } from './routes/api/wallistan/product.$slug'
import { Route as ApiWallistanOrdersLookupRouteImport } from './routes/api/wallistan/orders.lookup'
import { Route as ApiWallistanOrdersIdRouteImport } from './routes/api/wallistan/orders.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrderRoute = CustomOrderRouteImport.update({
  id: '/custom-order',
  path: '/custom-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiWoocommerceProductsRoute = ApiWoocommerceProductsRouteImport.update({
  id: '/api/woocommerce/products',
  path: '/api/woocommerce/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWoocommerceOrdersRoute = ApiWoocommerceOrdersRouteImport.update({
  id: '/api/woocommerce/orders',
  path: '/api/woocommerce/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWoocommerceCategoriesRoute =
  ApiWoocommerceCategoriesRouteImport.update({
    id: '/api/woocommerce/categories',
    path: '/api/woocommerce/categories',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWallistanProductsRoute = ApiWallistanProductsRouteImport.update({
  id: '/api/wallistan/products',
  path: '/api/wallistan/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWallistanOrdersRoute = ApiWallistanOrdersRouteImport.update({
  id: '/api/wallistan/orders',
  path: '/api/wallistan/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWallistanCategoriesRoute = ApiWallistanCategoriesRouteImport.update({
  id: '/api/wallistan/categories',
  path: '/api/wallistan/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWoocommerceProductSlugRoute =
  ApiWoocommerceProductSlugRouteImport.update({
    id: '/api/woocommerce/product/$slug',
    path: '/api/woocommerce/product/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWoocommerceOrdersLookupRoute =
  ApiWoocommerceOrdersLookupRouteImport.update({
    id: '/lookup',
    path: '/lookup',
    getParentRoute: () => ApiWoocommerceOrdersRoute,
  } as any)
const ApiWoocommerceOrdersIdRoute = ApiWoocommerceOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWoocommerceOrdersRoute,
} as any)
const ApiWallistanProductSlugRoute = ApiWallistanProductSlugRouteImport.update({
  id: '/api/wallistan/product/$slug',
  path: '/api/wallistan/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWallistanOrdersLookupRoute =
  ApiWallistanOrdersLookupRouteImport.update({
    id: '/lookup',
    path: '/lookup',
    getParentRoute: () => ApiWallistanOrdersRoute,
  } as any)
const ApiWallistanOrdersIdRoute = ApiWallistanOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWallistanOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/faq': typeof FaqRoute
  '/orders': typeof OrdersRouteWithChildren
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/wallistan/categories': typeof ApiWallistanCategoriesRoute
  '/api/wallistan/orders': typeof ApiWallistanOrdersRouteWithChildren
  '/api/wallistan/products': typeof ApiWallistanProductsRoute
  '/api/woocommerce/categories': typeof ApiWoocommerceCategoriesRoute
  '/api/woocommerce/orders': typeof ApiWoocommerceOrdersRouteWithChildren
  '/api/woocommerce/products': typeof ApiWoocommerceProductsRoute
  '/api/wallistan/orders/$id': typeof ApiWallistanOrdersIdRoute
  '/api/wallistan/orders/lookup': typeof ApiWallistanOrdersLookupRoute
  '/api/wallistan/product/$slug': typeof ApiWallistanProductSlugRoute
  '/api/woocommerce/orders/$id': typeof ApiWoocommerceOrdersIdRoute
  '/api/woocommerce/orders/lookup': typeof ApiWoocommerceOrdersLookupRoute
  '/api/woocommerce/product/$slug': typeof ApiWoocommerceProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/faq': typeof FaqRoute
  '/orders': typeof OrdersRouteWithChildren
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/wallistan/categories': typeof ApiWallistanCategoriesRoute
  '/api/wallistan/orders': typeof ApiWallistanOrdersRouteWithChildren
  '/api/wallistan/products': typeof ApiWallistanProductsRoute
  '/api/woocommerce/categories': typeof ApiWoocommerceCategoriesRoute
  '/api/woocommerce/orders': typeof ApiWoocommerceOrdersRouteWithChildren
  '/api/woocommerce/products': typeof ApiWoocommerceProductsRoute
  '/api/wallistan/orders/$id': typeof ApiWallistanOrdersIdRoute
  '/api/wallistan/orders/lookup': typeof ApiWallistanOrdersLookupRoute
  '/api/wallistan/product/$slug': typeof ApiWallistanProductSlugRoute
  '/api/woocommerce/orders/$id': typeof ApiWoocommerceOrdersIdRoute
  '/api/woocommerce/orders/lookup': typeof ApiWoocommerceOrdersLookupRoute
  '/api/woocommerce/product/$slug': typeof ApiWoocommerceProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/faq': typeof FaqRoute
  '/orders': typeof OrdersRouteWithChildren
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/wallistan/categories': typeof ApiWallistanCategoriesRoute
  '/api/wallistan/orders': typeof ApiWallistanOrdersRouteWithChildren
  '/api/wallistan/products': typeof ApiWallistanProductsRoute
  '/api/woocommerce/categories': typeof ApiWoocommerceCategoriesRoute
  '/api/woocommerce/orders': typeof ApiWoocommerceOrdersRouteWithChildren
  '/api/woocommerce/products': typeof ApiWoocommerceProductsRoute
  '/api/wallistan/orders/$id': typeof ApiWallistanOrdersIdRoute
  '/api/wallistan/orders/lookup': typeof ApiWallistanOrdersLookupRoute
  '/api/wallistan/product/$slug': typeof ApiWallistanProductSlugRoute
  '/api/woocommerce/orders/$id': typeof ApiWoocommerceOrdersIdRoute
  '/api/woocommerce/orders/lookup': typeof ApiWoocommerceOrdersLookupRoute
  '/api/woocommerce/product/$slug': typeof ApiWoocommerceProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom-order'
    | '/faq'
    | '/orders'
    | '/shop'
    | '/sitemap.xml'
    | '/wishlist'
    | '/blog/$slug'
    | '/category/$slug'
    | '/orders/$id'
    | '/product/$slug'
    | '/api/wallistan/categories'
    | '/api/wallistan/orders'
    | '/api/wallistan/products'
    | '/api/woocommerce/categories'
    | '/api/woocommerce/orders'
    | '/api/woocommerce/products'
    | '/api/wallistan/orders/$id'
    | '/api/wallistan/orders/lookup'
    | '/api/wallistan/product/$slug'
    | '/api/woocommerce/orders/$id'
    | '/api/woocommerce/orders/lookup'
    | '/api/woocommerce/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom-order'
    | '/faq'
    | '/orders'
    | '/shop'
    | '/sitemap.xml'
    | '/wishlist'
    | '/blog/$slug'
    | '/category/$slug'
    | '/orders/$id'
    | '/product/$slug'
    | '/api/wallistan/categories'
    | '/api/wallistan/orders'
    | '/api/wallistan/products'
    | '/api/woocommerce/categories'
    | '/api/woocommerce/orders'
    | '/api/woocommerce/products'
    | '/api/wallistan/orders/$id'
    | '/api/wallistan/orders/lookup'
    | '/api/wallistan/product/$slug'
    | '/api/woocommerce/orders/$id'
    | '/api/woocommerce/orders/lookup'
    | '/api/woocommerce/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom-order'
    | '/faq'
    | '/orders'
    | '/shop'
    | '/sitemap.xml'
    | '/wishlist'
    | '/blog/$slug'
    | '/category/$slug'
    | '/orders/$id'
    | '/product/$slug'
    | '/api/wallistan/categories'
    | '/api/wallistan/orders'
    | '/api/wallistan/products'
    | '/api/woocommerce/categories'
    | '/api/woocommerce/orders'
    | '/api/woocommerce/products'
    | '/api/wallistan/orders/$id'
    | '/api/wallistan/orders/lookup'
    | '/api/wallistan/product/$slug'
    | '/api/woocommerce/orders/$id'
    | '/api/woocommerce/orders/lookup'
    | '/api/woocommerce/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CustomOrderRoute: typeof CustomOrderRoute
  FaqRoute: typeof FaqRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiWallistanCategoriesRoute: typeof ApiWallistanCategoriesRoute
  ApiWallistanOrdersRoute: typeof ApiWallistanOrdersRouteWithChildren
  ApiWallistanProductsRoute: typeof ApiWallistanProductsRoute
  ApiWoocommerceCategoriesRoute: typeof ApiWoocommerceCategoriesRoute
  ApiWoocommerceOrdersRoute: typeof ApiWoocommerceOrdersRouteWithChildren
  ApiWoocommerceProductsRoute: typeof ApiWoocommerceProductsRoute
  ApiWallistanProductSlugRoute: typeof ApiWallistanProductSlugRoute
  ApiWoocommerceProductSlugRoute: typeof ApiWoocommerceProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-order': {
      id: '/custom-order'
      path: '/custom-order'
      fullPath: '/custom-order'
      preLoaderRoute: typeof CustomOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/woocommerce/products': {
      id: '/api/woocommerce/products'
      path: '/api/woocommerce/products'
      fullPath: '/api/woocommerce/products'
      preLoaderRoute: typeof ApiWoocommerceProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/woocommerce/orders': {
      id: '/api/woocommerce/orders'
      path: '/api/woocommerce/orders'
      fullPath: '/api/woocommerce/orders'
      preLoaderRoute: typeof ApiWoocommerceOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/woocommerce/categories': {
      id: '/api/woocommerce/categories'
      path: '/api/woocommerce/categories'
      fullPath: '/api/woocommerce/categories'
      preLoaderRoute: typeof ApiWoocommerceCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallistan/products': {
      id: '/api/wallistan/products'
      path: '/api/wallistan/products'
      fullPath: '/api/wallistan/products'
      preLoaderRoute: typeof ApiWallistanProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallistan/orders': {
      id: '/api/wallistan/orders'
      path: '/api/wallistan/orders'
      fullPath: '/api/wallistan/orders'
      preLoaderRoute: typeof ApiWallistanOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallistan/categories': {
      id: '/api/wallistan/categories'
      path: '/api/wallistan/categories'
      fullPath: '/api/wallistan/categories'
      preLoaderRoute: typeof ApiWallistanCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/woocommerce/product/$slug': {
      id: '/api/woocommerce/product/$slug'
      path: '/api/woocommerce/product/$slug'
      fullPath: '/api/woocommerce/product/$slug'
      preLoaderRoute: typeof ApiWoocommerceProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/woocommerce/orders/lookup': {
      id: '/api/woocommerce/orders/lookup'
      path: '/lookup'
      fullPath: '/api/woocommerce/orders/lookup'
      preLoaderRoute: typeof ApiWoocommerceOrdersLookupRouteImport
      parentRoute: typeof ApiWoocommerceOrdersRoute
    }
    '/api/woocommerce/orders/$id': {
      id: '/api/woocommerce/orders/$id'
      path: '/$id'
      fullPath: '/api/woocommerce/orders/$id'
      preLoaderRoute: typeof ApiWoocommerceOrdersIdRouteImport
      parentRoute: typeof ApiWoocommerceOrdersRoute
    }
    '/api/wallistan/product/$slug': {
      id: '/api/wallistan/product/$slug'
      path: '/api/wallistan/product/$slug'
      fullPath: '/api/wallistan/product/$slug'
      preLoaderRoute: typeof ApiWallistanProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallistan/orders/lookup': {
      id: '/api/wallistan/orders/lookup'
      path: '/lookup'
      fullPath: '/api/wallistan/orders/lookup'
      preLoaderRoute: typeof ApiWallistanOrdersLookupRouteImport
      parentRoute: typeof ApiWallistanOrdersRoute
    }
    '/api/wallistan/orders/$id': {
      id: '/api/wallistan/orders/$id'
      path: '/$id'
      fullPath: '/api/wallistan/orders/$id'
      preLoaderRoute: typeof ApiWallistanOrdersIdRouteImport
      parentRoute: typeof ApiWallistanOrdersRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ApiWallistanOrdersRouteChildren {
  ApiWallistanOrdersIdRoute: typeof ApiWallistanOrdersIdRoute
  ApiWallistanOrdersLookupRoute: typeof ApiWallistanOrdersLookupRoute
}

const ApiWallistanOrdersRouteChildren: ApiWallistanOrdersRouteChildren = {
  ApiWallistanOrdersIdRoute: ApiWallistanOrdersIdRoute,
  ApiWallistanOrdersLookupRoute: ApiWallistanOrdersLookupRoute,
}

const ApiWallistanOrdersRouteWithChildren =
  ApiWallistanOrdersRoute._addFileChildren(ApiWallistanOrdersRouteChildren)

interface ApiWoocommerceOrdersRouteChildren {
  ApiWoocommerceOrdersIdRoute: typeof ApiWoocommerceOrdersIdRoute
  ApiWoocommerceOrdersLookupRoute: typeof ApiWoocommerceOrdersLookupRoute
}

const ApiWoocommerceOrdersRouteChildren: ApiWoocommerceOrdersRouteChildren = {
  ApiWoocommerceOrdersIdRoute: ApiWoocommerceOrdersIdRoute,
  ApiWoocommerceOrdersLookupRoute: ApiWoocommerceOrdersLookupRoute,
}

const ApiWoocommerceOrdersRouteWithChildren =
  ApiWoocommerceOrdersRoute._addFileChildren(ApiWoocommerceOrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CustomOrderRoute: CustomOrderRoute,
  FaqRoute: FaqRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiWallistanCategoriesRoute: ApiWallistanCategoriesRoute,
  ApiWallistanOrdersRoute: ApiWallistanOrdersRouteWithChildren,
  ApiWallistanProductsRoute: ApiWallistanProductsRoute,
  ApiWoocommerceCategoriesRoute: ApiWoocommerceCategoriesRoute,
  ApiWoocommerceOrdersRoute: ApiWoocommerceOrdersRouteWithChildren,
  ApiWoocommerceProductsRoute: ApiWoocommerceProductsRoute,
  ApiWallistanProductSlugRoute: ApiWallistanProductSlugRoute,
  ApiWoocommerceProductSlugRoute: ApiWoocommerceProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
